export const HOME_GET_WEATHER_BEGIN = 'HOME_GET_WEATHER_BEGIN';
export const HOME_GET_WEATHER_SUCCESS = 'HOME_GET_WEATHER_SUCCESS';
export const HOME_GET_WEATHER_FAILURE = 'HOME_GET_WEATHER_FAILURE';
export const HOME_GET_WEATHER_DISMISS_ERROR = 'HOME_GET_WEATHER_DISMISS_ERROR';
export const HOME_GET_CURRENT_WEATHER_BEGIN = 'HOME_GET_CURRENT_WEATHER_BEGIN';
export const HOME_GET_CURRENT_WEATHER_SUCCESS = 'HOME_GET_CURRENT_WEATHER_SUCCESS';
export const HOME_GET_CURRENT_WEATHER_FAILURE = 'HOME_GET_CURRENT_WEATHER_FAILURE';
export const HOME_GET_CURRENT_WEATHER_DISMISS_ERROR = 'HOME_GET_CURRENT_WEATHER_DISMISS_ERROR';
